import { StyleSheet } from 'react-native';

import { Colors, Fonts } from '@/constants/theme';

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.cream,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 31,
    paddingTop: 25,
    paddingBottom: 116,
  },
  greeting: {
    color: Colors.clay,
    fontFamily: Fonts.sans,
    fontSize: 16,
    marginBottom: 2,
  },
  userName: {
    color: '#141412',
    fontFamily: Fonts.serif,
    fontSize: 38,
    fontStyle: 'italic',
  },
  profileButton: {
    position: 'absolute',
    top: 25,
    right: 31,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F1EADB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: Colors.brandGreen,
    fontFamily: Fonts.serif,
    fontSize: 24,
  },
  searchBar: {
    height: 66,
    marginTop: 31,
    backgroundColor: '#FFFFFF',
    borderColor: '#EEE5D7',
    borderWidth: 1,
    borderRadius: 34,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 14,
    shadowColor: '#BDAF96',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  searchIcon: {
    color: '#77736C',
    fontSize: 28,
    lineHeight: 28,
  },
  searchPlaceholder: {
    color: '#77736C',
    fontFamily: Fonts.sans,
    fontSize: 16,
  },
  searchInput: { flex: 1, color: '#181816', fontFamily: Fonts.sans, fontSize: 16, paddingVertical: 0 },
  filterLabel: { color: '#706C64', fontFamily: Fonts.sans, fontSize: 12, fontWeight: '700', letterSpacing: 0.4, marginTop: 24, marginBottom: 7 },
  filterButton: { height: 61, borderRadius: 32, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, justifyContent: 'center', paddingHorizontal: 20, shadowColor: '#BDAF96', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 2 },
  filterInput: { height: 61, borderRadius: 32, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, justifyContent: 'center', paddingHorizontal: 20, color: '#181816', fontFamily: Fonts.sans, fontSize: 16, shadowColor: '#BDAF96', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 2 },
  filterText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 16 },
  dropdownWrapper: { position: 'relative', zIndex: 5 },
  dropdownArrow: { position: 'absolute', right: 22, color: '#756F65', fontSize: 20 },
  dropdownOptions: { backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, borderRadius: 18, marginTop: 6, overflow: 'hidden', shadowColor: '#BDAF96', shadowOpacity: 0.16, shadowRadius: 8, elevation: 4 },
  dropdownOption: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 20, borderBottomColor: '#F1EADB', borderBottomWidth: 1 },
  shoppingButton: {
    height: 55,
    marginTop: 30,
    borderRadius: 30,
    backgroundColor: Colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  shoppingIcon: {
    color: Colors.cream,
    fontSize: 22,
  },
  shoppingLabel: {
    color: Colors.cream,
    fontFamily: Fonts.sans,
    fontSize: 17,
    fontWeight: '700',
  },
  sectionHeader: {
    marginTop: 52,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#181816',
    fontFamily: Fonts.serif,
    fontSize: 25,
    fontStyle: 'italic',
  },
  seeAll: {
    color: Colors.clay,
    fontFamily: Fonts.sans,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  horizontalList: {
    overflow: 'visible',
  },
  featureCard: {
    width: 350,
    marginRight: 20,
  },
  featureImage: {
    height: 300,
    backgroundColor: '#F1EADB',
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  featurePhoto: { width: '100%', height: '100%', borderRadius: 34 },
  imageIcon: {
    color: '#C8C2B3',
    fontSize: 56,
  },
  seasonBadge: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#8D806B',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  seasonText: {
    color: Colors.brandGreen,
    fontFamily: Fonts.sans,
    fontSize: 12,
    fontWeight: '700',
  },
  featureTitle: {
    color: '#181816',
    fontFamily: Fonts.serif,
    fontSize: 22,
    lineHeight: 27,
    marginTop: 16,
  },
  featureMeta: {
    color: '#756F65',
    fontFamily: Fonts.sans,
    fontSize: 14,
    marginTop: 5,
  },
  smallCard: {
    width: 240,
    marginRight: 20,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderColor: '#EEE5D7',
    borderWidth: 1,
    borderRadius: 28,
    shadowColor: '#BDAF96',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  smallImage: {
    height: 205,
    backgroundColor: '#F1EADB',
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  smallPhoto: { width: '100%', height: '100%', borderRadius: 23 },
  smallTitle: {
    color: '#181816',
    fontFamily: Fonts.serif,
    fontSize: 18,
    lineHeight: 23,
    marginTop: 14,
  },
  rating: {
    color: '#151513',
    fontFamily: Fonts.sans,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  star: {
    color: '#DCA52A',
    fontSize: 16,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 87,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 38,
    borderTopRightRadius: 38,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: '#A99B85',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 9,
    elevation: 8,
  },
  navItem: {
    alignItems: 'center',
    gap: 4,
    minWidth: 62,
  },
  navIcon: {
    color: '#7F7A71',
    fontSize: 28,
    height: 30,
  },
  navIconActive: {
    color: Colors.brandGreen,
  },
  navLabel: {
    color: '#706C64',
    fontFamily: Fonts.sans,
    fontSize: 12,
  },
  navLabelActive: {
    color: Colors.brandGreen,
  },
  favoriteTabs: { height: 60, borderRadius: 32, backgroundColor: '#F1EADB', flexDirection: 'row', padding: 5, marginTop: 25 },
  favoriteTab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 28 },
  favoriteTabActive: { backgroundColor: '#FFFFFF', shadowColor: '#BDAF96', shadowOpacity: 0.18, shadowRadius: 8, elevation: 2 },
  favoriteTabText: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, fontWeight: '600' },
  listCreateRow: { flexDirection: 'row', gap: 10, marginTop: 20 },
  listInput: { flex: 1, height: 52, borderRadius: 27, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, paddingHorizontal: 18, color: '#181816' },
  listCreateButton: { width: 52, height: 52, borderRadius: 27, backgroundColor: Colors.clay, alignItems: 'center', justifyContent: 'center' },
  listCreateText: { color: Colors.cream, fontSize: 28 },
  folderRow: { height: 74, paddingHorizontal: 24, borderRadius: 28, backgroundColor: '#F7E5DC', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
  folderName: { color: '#181816', fontFamily: Fonts.serif, fontSize: 20, fontStyle: 'italic' },
  folderCount: { color: Colors.clay, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '700' },
  emptyState: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 16, textAlign: 'center', marginTop: 30 },
});
