import { StyleSheet } from 'react-native';

import { Colors, Fonts } from '@/constants/theme';

export const recipeStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.cream },
  safeArea: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  header: {
    height: 69,
    paddingHorizontal: 18,
    borderBottomColor: '#E8E1D2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  backButton: {
    width: 36, height: 36, borderRadius: 20, backgroundColor: '#F1EADB',
    alignItems: 'center', justifyContent: 'center',
  },
  backArrow: { color: '#1E1E1B', fontSize: 28, lineHeight: 30, marginTop: -3 },
  headerTitle: { flex: 1, color: '#181816', fontFamily: Fonts.serif, fontSize: 18, fontStyle: 'italic' },
  headerSave: { width: 44, height: 44, borderRadius: 24, backgroundColor: '#F1EADB', alignItems: 'center', justifyContent: 'center' },
  headerSaveIcon: { color: Colors.brandGreen, fontSize: 25 },
  hero: { height: 280, margin: 24, borderRadius: 32, backgroundColor: '#F1EADB', alignItems: 'center', justifyContent: 'center' },
  heroImage: { width: '100%', height: '100%', borderRadius: 32 },
  heroIcon: { color: '#C8C2B3', fontSize: 72 },
  content: { paddingHorizontal: 26 },
  title: { color: '#181816', fontFamily: Fonts.serif, fontSize: 30, lineHeight: 36, fontStyle: 'italic' },
  meta: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 14, marginTop: 9 },
  description: { color: '#45413B', fontFamily: Fonts.sans, fontSize: 15, lineHeight: 23, marginTop: 25 },
  errorText: { color: '#A33228', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, marginTop: 12 },
  stats: { flexDirection: 'row', gap: 22, marginTop: 24 },
  stat: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 14 },
  tabs: { height: 60, borderRadius: 32, backgroundColor: '#F1EADB', flexDirection: 'row', padding: 5, marginTop: 25, marginBottom: 22 },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 28 },
  activeTab: { backgroundColor: '#FFFFFF', shadowColor: '#BDAF96', shadowOpacity: 0.18, shadowRadius: 8, elevation: 2 },
  tabText: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 16, fontWeight: '600' },
  activeTabText: { color: Colors.brandGreen },
  tabContent: { gap: 12 },
  mediaActions: { flexDirection: 'row', gap: 10, marginBottom: 4 },
  mediaAction: { flex: 1, minHeight: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  audioAction: { backgroundColor: Colors.brandGreen },
  videoAction: { backgroundColor: Colors.clay },
  mediaActionText: { color: Colors.cream, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  mediaPlayer: { width: '100%', aspectRatio: 16 / 9, borderRadius: 16, overflow: 'hidden', backgroundColor: '#181816', marginBottom: 8 },
  ingredientRow: { minHeight: 62, paddingHorizontal: 20, borderRadius: 32, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  addToList: { color: Colors.clay, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '700' },
  stepRow: { padding: 20, borderRadius: 24, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, flexDirection: 'row', alignItems: 'flex-start', gap: 16 },
  stepNumber: { width: 31, height: 31, borderRadius: 18, backgroundColor: '#F7E5DC', color: Colors.clay, fontFamily: Fonts.serif, fontSize: 16, textAlign: 'center', paddingTop: 5 },
  stepText: { flex: 1, color: '#181816', fontFamily: Fonts.sans, fontSize: 15, lineHeight: 22 },
  commentCard: { padding: 20, borderRadius: 24, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1 },
  commentLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  commentAuthor: { color: '#181816', fontFamily: Fonts.serif, fontSize: 18, fontStyle: 'italic' },
  commentText: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, lineHeight: 22, marginTop: 10 },
  flag: { color: '#D42F2F', fontSize: 22 },
  commentInput: { minHeight: 52, borderRadius: 28, borderWidth: 1, borderColor: '#EDE5D7', backgroundColor: '#FFFFFF', paddingHorizontal: 18, color: '#181816', fontFamily: Fonts.sans },
  commentButton: { height: 56, borderRadius: 30, backgroundColor: '#F1EADB', alignItems: 'center', justifyContent: 'center' },
  reportLink: { color: '#D42F2F', fontFamily: Fonts.sans, fontSize: 14, textAlign: 'center', textDecorationLine: 'underline', marginTop: 38 },
  bottomActions: { flexDirection: 'row', gap: 15, marginTop: 30, marginBottom: 24 },
  rateButton: { flex: 1, height: 64, borderRadius: 34, backgroundColor: '#F1EADB', alignItems: 'center', justifyContent: 'center' },
  saveButton: { flex: 1, height: 64, borderRadius: 34, backgroundColor: Colors.brandGreen, alignItems: 'center', justifyContent: 'center' },
  actionText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 16, fontWeight: '700' },
  saveText: { color: Colors.cream, fontFamily: Fonts.sans, fontSize: 16, fontWeight: '700' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.32)', justifyContent: 'flex-end' },
  reportModal: { backgroundColor: Colors.cream, borderTopLeftRadius: 38, borderTopRightRadius: 38, padding: 30, paddingBottom: 38 },
  modalTitle: { color: '#D42F2F', fontFamily: Fonts.serif, fontStyle: 'italic', fontSize: 28, marginBottom: 28 },
  modalTitleSave: { color: '#181816', fontFamily: Fonts.serif, fontStyle: 'italic', fontSize: 28, marginBottom: 24 },
  saveOption: { minHeight: 56, borderRadius: 28, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, justifyContent: 'center', paddingHorizontal: 20, marginBottom: 12 },
  saveOptionText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 15 },
  modalLabel: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 12, fontWeight: '700', marginTop: 12, marginBottom: 9 },
  reasonList: { backgroundColor: '#FFFFFF', borderRadius: 20, paddingVertical: 4 },
  reasonRow: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 10 },
  radio: { width: 20, height: 20, borderRadius: 12, borderWidth: 1, borderColor: '#C8C0B3' },
  radioSelected: { backgroundColor: Colors.brandGreen, borderColor: Colors.brandGreen },
  reasonText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 14 },
  reportInput: { minHeight: 80, borderRadius: 18, borderColor: '#EDE5D7', borderWidth: 1, backgroundColor: '#FFFFFF', padding: 14, textAlignVertical: 'top', color: '#181816' },
  modalActions: { flexDirection: 'row', gap: 15, marginTop: 24 },
  cancelButton: { flex: 1, height: 58, borderRadius: 30, backgroundColor: '#F1EADB', alignItems: 'center', justifyContent: 'center' },
  dangerButton: { flex: 1, height: 58, borderRadius: 30, backgroundColor: '#D42F2F', alignItems: 'center', justifyContent: 'center' },
  ratingHint: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, textAlign: 'center', marginBottom: 18 },
  starPicker: { flexDirection: 'row', justifyContent: 'center', gap: 9, marginBottom: 26 },
  ratingStar: { color: '#D9D2C4', fontSize: 42 },
  ratingStarActive: { color: '#DCA52A' },
  disabledButton: { opacity: 0.45 },
  feedbackToast: { position: 'absolute', left: 22, right: 22, bottom: 24, minHeight: 58, borderRadius: 18, backgroundColor: Colors.brandGreen, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 10, shadowColor: '#000000', shadowOpacity: 0.2, shadowRadius: 8, elevation: 5 },
  feedbackIcon: { color: Colors.cream, fontSize: 21, fontWeight: '700' },
  feedbackText: { flex: 1, color: Colors.cream, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '600' },
  sectionTitle: { color: '#181816', fontFamily: Fonts.serif, fontSize: 24, fontStyle: 'italic', marginTop: 30, marginBottom: 14 },
  ingredient: { color: '#45413B', fontFamily: Fonts.sans, fontSize: 15, paddingVertical: 8 },
  favoriteButton: { position: 'absolute', right: 25, top: 25, width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  favoriteIcon: { color: Colors.clay, fontSize: 26 },
  favoriteIconActive: { color: Colors.brandGreen },
  removeSaveOption: { minHeight: 56, borderRadius: 28, backgroundColor: '#F7E5DC', justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20, marginBottom: 12 },
  removeSaveText: { color: Colors.clay, fontFamily: Fonts.sans, fontSize: 15, fontWeight: '700' },
});
