import { StyleSheet } from 'react-native';

import { Colors, Fonts } from '@/constants/theme';

export const userRecipesStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.cream },
  safeArea: { flex: 1 },
  content: { padding: 24, paddingBottom: 110, gap: 16 },
  heading: { color: '#181816', fontFamily: Fonts.serif, fontSize: 29, fontStyle: 'italic', marginBottom: 4 },
  description: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, lineHeight: 22, marginBottom: 6 },
  recipeRow: { padding: 20, backgroundColor: '#FFFFFF', borderColor: '#EDE5D7', borderWidth: 1, borderRadius: 20, gap: 8 },
  recipeTitle: { color: '#181816', fontFamily: Fonts.serif, fontSize: 21 },
  recipeDescription: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20 },
  recipeMeta: { color: Colors.brandGreen, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '700', marginTop: 4 },
  recipeActions: { flexDirection: 'row', gap: 10, marginTop: 8 },
  editRecipeButton: { flex: 1, minHeight: 46, borderRadius: 14, backgroundColor: Colors.brandGreen, alignItems: 'center', justifyContent: 'center' },
  deleteRecipeButton: { flex: 1, minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: Colors.clay, alignItems: 'center', justifyContent: 'center' },
  recipeActionText: { color: Colors.cream, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  deleteRecipeText: { color: Colors.clay, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  empty: { paddingVertical: 34, alignItems: 'center', gap: 10 },
  emptyText: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, textAlign: 'center' },
  message: { color: Colors.clay, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20 },
  form: { padding: 22, gap: 18 },
  sectionTitle: { color: '#181816', fontFamily: Fonts.serif, fontSize: 23, fontStyle: 'italic', marginTop: 8 },
  twoColumns: { flexDirection: 'row', gap: 12 },
  halfField: { flex: 1 },
  multiline: { minHeight: 100, height: undefined, paddingTop: 14, textAlignVertical: 'top' },
  smallMultiline: { minHeight: 82, height: undefined, paddingTop: 14, textAlignVertical: 'top' },
  row: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  rowField: { flex: 1 },
  removeButton: { minWidth: 40, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  removeText: { color: Colors.clay, fontSize: 23 },
  addButton: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-start' },
  addText: { color: Colors.brandGreen, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  choices: { flexDirection: 'row', gap: 8 },
  choice: { flex: 1, minHeight: 46, borderRadius: 23, borderColor: '#EDE5D7', borderWidth: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  choiceSelected: { borderColor: Colors.brandGreen, backgroundColor: Colors.brandGreen },
  choiceText: { color: '#514F49', fontFamily: Fonts.sans, fontSize: 13 },
  choiceTextSelected: { color: Colors.cream, fontWeight: '700' },
  mediaSection: { gap: 12 },
  mediaButton: { minHeight: 52, borderRadius: 27, borderWidth: 1, borderColor: '#DAD1C1', backgroundColor: '#FFFFFF', justifyContent: 'center', paddingHorizontal: 18 },
  mediaButtonText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 15 },
  imagePreview: { width: '100%', height: 220, borderRadius: 18, backgroundColor: '#F1EADB' },
  error: { color: '#A33228', fontFamily: Fonts.sans, fontSize: 14 },
  success: { color: Colors.brandGreen, fontFamily: Fonts.sans, fontSize: 14 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.38)', justifyContent: 'center', padding: 24 },
  deleteDialog: { backgroundColor: Colors.cream, borderRadius: 20, padding: 24, gap: 14 },
  deleteTitle: { color: '#181816', fontFamily: Fonts.serif, fontSize: 24, fontStyle: 'italic' },
  deleteDescription: { color: '#756F65', fontFamily: Fonts.sans, fontSize: 15, lineHeight: 22 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 8 },
  cancelButton: { flex: 1, minHeight: 48, borderRadius: 14, backgroundColor: '#EAE4D8', alignItems: 'center', justifyContent: 'center' },
  cancelText: { color: '#181816', fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  confirmDeleteButton: { flex: 1, minHeight: 48, borderRadius: 14, backgroundColor: Colors.clay, alignItems: 'center', justifyContent: 'center' },
  confirmDeleteText: { color: Colors.cream, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
  disabledButton: { opacity: 0.6 },
});